config/routes.rb
TodoApp::Application.routes.draw do

  resources :todos do
    member do
      match :done
    end
  end


  root :to => "home#index"
  
  get :signin, to: 'sessions#new'
  get :signout, to: 'sessions#destroy'
  
  get '/auth/facebook/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  
  resources :users
end

app/models/todo.rb
class Todo
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes 
  
  field :title, type: String
  field :user_id, type: Integer
  field :description, type: String
  field :due_at, type: Time
  field :done_at, type: Time
  
  scope :pending, where(done_at: nil)
  
  belongs_to :user
  
  validates :title,
    presence: true
  
  def done!
    self.update_attributes done_at: Time.now
  end
  
  def undone!
    self.update_attributes done_at: nil
  end
  
  def done?
    self.done_at?
  end
  
end

app/models/user.rb
class User
  include Mongoid::Document
  field :provider, type: String
  field :uid, type: String
  field :name, type: String
  field :email, type: String
  attr_accessible :provider, :uid, :name, :email
  # run 'rake db:mongoid:create_indexes' to create indexes
  index({ email: 1 }, { unique: true, background: true })
  
  has_many :todos

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end
  
  def picture
    "https://graph.facebook.com/#{uid}/picture"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :redirect_logged_user!, only: :index, if: :user_signed_in?
  
  def index
  end
  
  def redirect_logged_user!
    redirect_to todos_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end


  def create
    auth = request.env["omniauth.auth"]

    user = User.where({
      provider: auth['provider'], 
      uid: auth['uid'].to_s
    }).first || User.create_with_omniauth(auth)
    
    session[:user_id] = user.id
    
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /todos
  # GET /todos.json
  def index
    @todos = current_user.todos.pending
    @todo = current_user.todos.build

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todos }
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @todo = current_user.todos.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/new
  # GET /todos/new.json
  def new
    @todo = current_user.todos.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = current_user.todos.build(params[:todo])

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path, notice: 'Todo was successfully created.' }
        format.json { render json: @todo, status: :created, location: @todo }
      else
        format.html { render action: "new" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @todo = current_user.todos.find(params[:id])

    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = current_user.todos.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end
  
  def done
    @todo = current_user.todos.find(params[:id])
    @todo.done!
    
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Todoapp", root_path, :class => 'brand' %>

<span class="pull-right">
  <%= image_tag current_user.picture, size: '50x50' if current_user %>  
</span>
<ul class="nav pull-right">
  <% if user_signed_in? %>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <%= current_user.name %>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><%= link_to 'Preferences', edit_user_path(current_user) %></li>
        <li><%= link_to 'Logout', signout_path %></li>
      </ul>
    </li>
  <% else %>
    <li><%= link_to 'Login', signin_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Todoapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Todoapp" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/todos/_form.html.erb
<%= simple_form_for(@todo, html:{ class: "form-horizontal", style: 'margin:0'}) do |f| %>
  <%= f.error_notification %>

  <div class="modal-body">
    <%= f.input :title, input_html: {class: 'input-xlarge'} %>
    <%= f.input :description, as: :text, input_html: {class: 'input-xlarge', rows: 5} %>
    <%= f.input :due_at, as: :date, include_blank: true, input_html: {class: 'input-small', rows: 5} %>
  </div>

  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h2>Todos</h2>


<table class="table table-striped table-hover">
  <col width="20" />
  <col />
<% @todos.each do |todo| %>
  <tr>
    <td>
      <%= link_to done_todo_path(todo) do %>
        <i class='icon-check'></i>
      <% end %>
    </td>
    <td>
      <strong><%= todo.title %></strong>
      <% if todo.due_at? %>
      <span>(<%= I18n.l( todo.due_at.to_date, format: :long ) %>)</span>
      <% end %>
      <% if todo.description.present? %>
      <br><small><%= simple_format(todo.description) %></small>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />
<a href="#myModal" role="button" class="btn btn-small" data-toggle="modal"><i class="icon-edit"></i> New Todo</a>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="newTodoModal" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Add Todo</h3>
  </div>
  
  <%= render 'form' %>
</div>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @todo.title %>
</p>

<p>
  <b>User:</b>
  <%= @todo.user_id %>
</p>

<p>
  <b>Description:</b>
  <%= @todo.description %>
</p>

<p>
  <b>Due at:</b>
  <%= @todo.due_at %>
</p>

<p>
  <b>Done at:</b>
  <%= @todo.done_at %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>